# Generated by Django 5.1.4 on 2026-05-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='open_positions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
